### ISSUE TITLE
PabloUniform class design

### ISSUE THREAD

**Issue by pkestene** [optimad/bitpit#12]
I noticed that PabloUniform is overloading some member functions of the base class ParaTree but not all of them, and so some of the base class members are (accidentally ?) hidden in the derived class; I don't think this the intended behavior, maybe someone can clarify this.

Just as an example:
PabloTree defines 6 different versions of method "getNodes" with different signatures, while 
PabloUniform redefines 5 of them.
The problem is that the following public member of ParaTree 
const u32arr3vector & getNodes() const;
is not available in the derived class PabloUniform because it is hidden by other "getNodes" avaialble in the derived class.

I think, the above member getNodes() should also be available in the derived class. So a possible
solution is just to add in class PabloUniform declaration:
using ParaTree::getNodes; 

What do you think ?

**Comment by marcocisternino** [comment]
Hi pkestene,
Thanks for your contribute, I'll try to explain what we meant exposing only some of the ParaTree methods in PabloUniform:
ParaTree is the logical manager of the linear octree, meaning that he lives in a logical space where vertex coordinates are integers. PabloUniform should derive from ParaTree in order to introduce an affine transformation from the logical space to the physical one. In this context, we decided to avoid the user to call methods returning logical coordinates of the nodes. For the sake of truth, we did something that is not so good from a design point of view: in order to ease the user experience, we introduced in ParaTree a transformation from the logical space to the unit square. By this way the user, deriving from ParaTree to introduce his own transformation, could do it from the unit square to the physical domain, knowing nothing about logical coordinates.
The method you cited, the hidden getNodes, return a list of logical coordinates of all the nodes, that's why it should not be available in PabloUniform.
If you feel that some of the other ParaTree methods hidden to PabloUniform should be available in PabloUniform, please let us know.
Thanks!

**Comment by pkestene** [comment]
Ok that makes sense.
Thank you.

**Comment by marcocisternino** [comment]
This issue has not seen any recent activity. I'm closing the issue, but feel free to re-open a closed issue if needed.
