### ISSUE TITLE
Update Cmake minimum required version 

### ISSUE THREAD

**Issue by roccoarpa** [optimad/bitpit#186]
New releases of Cmake (3.20 in particular) are starting to tag version 2.8 as deprecated. 
Consider to pass to a newer version as "cmake_minimum_required" in biptit. For example, 3.4 should be just fine.
mimic side, we have no issues on the porting. Don't know if @marcocisternino has any. 
Anyway, I'll leave the decision to you.

**Comment by marcocisternino** [comment]
No special issue from my side. Cmake 3.13 is available on our facilities.

**Comment by andrea-iob** [comment]
It really comes down to what's the oldest distribution we want to support. Switching from CMake 2.8 to CMake 3.x would be really great. We kept compatibility with CMake 2.8 because we wanted to install bitpit on systems that were quite old and were still using CMake 2.8. If that requirement is now gone I'm happy to switch to CMake 3.X.
