### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by pkanninen** [optimad/bitpit#2]
Hi,

I get the error at the translation stage:

`[ 10%] Built target LEVELSET_TARGET_OBJECT
[ 13%] Built target COMMON_TARGET_OBJECT
[ 14%] Building CXX object src/CG/CMakeFiles/CG_TARGET_OBJECT.dir/CG_elem.cpp.o
In file included from /usr/include/c++/4.8.2/complex:45:0,
                 from /usr/include/c++/4.8.2/ccomplex:38,
                 from /usr/include/c++/4.8.2/complex.h:32,
                 from /usr/include/lapacke/lapacke.h:77,
                 from /home/Pekka/mimmo/bitpit/src/CG/CG_elem.cpp:30:
/usr/include/c++/4.8.2/sstream:63:3: error: template with C linkage
   template<typename _CharT, typename _Traits, typename _Alloc>
   ^
/usr/include/c++/4.8.2/sstream:271:3: error: template with C linkage
   template<typename _CharT, typename _Traits, typename _Alloc>`  

If I understand correctly this is symptom of " extern "C" " call. How avoid this problem? 

My Linux is Centos7 and gcc version is gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16).

BR/Pekka

**Comment by marcocisternino** [comment]
Hi pkanninen,
thanks for your help! The problem should come from lapacke inclusion. 
It's a known issue for old gcc (probably <= 4.8.2): https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59087
Pay attention to your gcc version, because from the compile error says you're using gcc 4.8.2.
We propose a workaround (coming from the link above) to include lapacke with a complex.h defining macro "I". In the bitpit branch fix.gcc.lapack.complex.include, you can find the proposed correction.
We kindly ask you to test and report the branch and if it works for you, we will merge it into the master.
Thanks for your help in bug reporting and for using bitpit.

**Comment by pkanninen** [comment]
Thanks a lot!
Now it works. Red Hat system gcc has been updated from 4.8.2 -> 4.8.5 but include/c++/4.8.5 still points to 4.8.2 ?

**Comment by andrea-iob** [comment]
The fix is on master and 1.4 branches.
