### ISSUE TITLE
volunstructured: Question - How could we get the complete list of edge neighbours?

### ISSUE THREAD

**Issue by DMurataj01** [optimad/bitpit#216]
Hi - I would like to get the complete list of edge neighbours, where the neighbours may also be on different levels i.e. subdivided or bigger than the cell we are calling `findCellEdgeNeighs` from.

Currently it appears like neighbours on different levels are not detected.

What would be the most efficient way to do this?

Kind Regards,
Denis

**Comment by andrea-iob** [comment]
At the moment, `volunstructured` works only with conformal meshes. Hanging nodes are not handled automatically by the bitpit library. Generation of adjacencies and neighbours is based on cell connectivity and hence it cannot handle hanging nodes. 

In order to add support for non-conformal meshes, some functions of `volunstructured` need to be re-implemented. It may be enough to re-implement a couple of functions (i.e., the function that evaluates vertex negihbours and the function that generates cell adjacencies, all other functions that evaluate the neighbours rely on one of these two functions). 

It may not be what you need, buy the mesh `voloctree` already supports non-conformal meshes.
