### ISSUE TITLE
Cannot build on Ubuntu 18.04

### ISSUE THREAD

**Issue by s1291** [optimad/bitpit#22]
Hello, 
I am trying to build bitpit on ubuntu 18.04.
I have installed the required libraries (`lapack`, `blas`, `libxml2`, ...etc). I have also build `PETSC` successfully following [these instructions](https://www.mcs.anl.gov/petsc/documentation/installation.html).
After that, I added the following to `~/.bashrc`
```bash
export PETSC_DIR='/mnt/d/Programs/mimmo_bitpit/petsc'
export PETSC_ARCH='arch-linux2-c-debug'
```
But when I try to build bitpit I get the following error:
```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  PETSc could not be found.  Be sure to set PETSC_DIR and PETSC_ARCH.
  (missing: PETSC_INCLUDES PETSC_LIBRARIES PETSC_EXECUTABLE_RUNS)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  external/PETSc/cmake/FindPETSc.cmake:348 (find_package_handle_standard_args)
  CMakeLists.txt:524 (find_package)
```

Thank you

**Comment by marcocisternino** [comment]
Hello s1291,
we are glad to know about your interest in bitpit (and mimmo I believe).
In order to help you, we need some more information about your PETSc installation.
I'm sorry if some of the next sentences could sound stupid, but I don't know anything about your system, therefore I will start from the basis.

Does "echo $PETSC_DIR" prints "/mnt/d/Programs/mimmo_bitpit/petsc" in bash?

If you completely followed the PETSc installation instructions, you should have launch "make install" with a value for the prefix configuration variable. If not, please install PETSc because you only built it.

If everything is clean, '/mnt/d/Programs/mimmo_bitpit/petsc' should be the value for prefix. Please, verify that the path /mnt/d/Programs/mimmo_bitpit/petsc contains the arch-linux2-c-debug folder.

If /mnt/d/Programs/mimmo_bitpit/petsc/arch-linux2-c-debug exists and /mnt/d/Programs/mimmo_bitpit/petsc' is the PETSc installation folder, configuring bitpit with cmake, please, force PETSC_DIR and PETSC_ARCH cmake variable to those values.

If /mnt/d/Programs/mimmo_bitpit/petsc' is the PETSc installation folder, but arch-linux2-c-debug does not exist, use ccmake on bitpit build folder to empty the cmake variable PETSC_ARCH and try again, please.

Unfortunately, I cannot say more than this from here.
Please, let me know if my suggestions work or if you need more help.

Thanks,

Marco Cisternino, PhD
marco.cisternino@optimad.it
_______________________________
OPTIMAD Engineering srl
Via Giacinto Collegno 18, Torino, Italia.
+3901119719782
www.optimad.it



________________________________________
Da: s1291 <notifications@github.com>
Inviato: mercoledì 30 ottobre 2019 18:37
A: optimad/bitpit
Cc: Subscribed
Oggetto: [optimad/bitpit] Cannot build on Ubuntu 18.04 (#22)

Hello,
I am trying to build bitpit on ubuntu 18.04.
I have installed the required libraries (lapack, blas, libxml2, ...etc). I have also build PETSC successfully following these instructions<https://www.mcs.anl.gov/petsc/documentation/installation.html>.
After that, I added the following to ~/.bashrc

export PETSC_DIR='/mnt/d/Programs/mimmo_bitpit/petsc'
export PETSC_ARCH='arch-linux2-c-debug'

But when I try to build bitpit I get the following error:

CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  PETSc could not be found.  Be sure to set PETSC_DIR and PETSC_ARCH.
  (missing: PETSC_INCLUDES PETSC_LIBRARIES PETSC_EXECUTABLE_RUNS)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  external/PETSc/cmake/FindPETSc.cmake:348 (find_package_handle_standard_args)
  CMakeLists.txt:524 (find_package)


Thank you

**Comment by s1291** [comment]
Hello, Thank you very much for your reply.
I think I forgot to: `make install` :grin:
However when I try to install using `sudo make install DESTDIR=/opt/petsc3.12`
it changes the DESTDIR to `/opt/petsc3.12/mnt/d/Programs/mimmo_bitpit/petsc`.

**Comment by marcocisternino** [comment]
What do you set as prefix in petsc configuration?

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by marcocisternino** [comment]
I believe the final DESTDIR is your set plus the prefix. Let's check what's your prefix...

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by s1291** [comment]
According to [this](https://stackoverflow.com/questions/45332075/installing-petsc-from-source-specified-destdir-same-as-current-petsc-dir-petsc) if the prefix is not set then `make install` doesn't make sense.
I moved to another PC, and I managed to install bitpit. I will try tomorrow to re-install it on that PC and report the steps.

**Comment by s1291** [comment]
Today I installed bitpit successfully again. Here is my conclusion:
- Build PETSc (you don't need to install it) and make sure that `PETSC_DIR` points to that location and `PETSC_ARCH` to something like: `arch-linux2-c-debug`. 
- The issue was that _CMake_ doesn't resolve these variables. So I have to specify them manually in `ccmake`.
but it still fails to generate the Makefile unless I start it with the following option:
```
ccmake -DPETSC_EXECUTABLE_RUNS=ON ..
```
