### ISSUE TITLE
IO:  STLReader::detectFormat returning FormatUnknown for STL case

### ISSUE THREAD

**Issue by kgkara** [optimad/bitpit#402]
When calling STLReader::detectFormat, it returns STLBase::Format::FormatUnknown for the attached STL case:
[case.stl.txt](https://github.com/optimad/bitpit/files/11732383/case.stl.txt)
Please remove the ".txt" extension to test it.

The input argument to the method is filename = "./geodata/case.stl"

The same file can be opened with paraview and other software.

**Comment by andrea-iob** [comment]
bitpit follows the [guidelines](https://en.wikipedia.org/wiki/STL_(file_format)) of wikipedia for the detection of the file format, in this case this is the relevant part: "An ASCII STL file begins with the line "solid name", where name is an optional string (though if name is omitted there must still be a space after solid, for compatibility with some software)."

The attached file doesn't contain a space after the solid word. 

After removing the requirement of an empty space after the solid word, the file is correctly detected as ASCII. The same happens if the space is added in the file. 

I don't have a strong opinion on this. We can remove the requirement of the space character.
