### ISSUE TITLE
build error by CMake

### ISSUE THREAD

**Issue by yoonil4** [optimad/bitpit#6]
hi, I tried to build bitpit by CMake, but I have a problem. .

Below is the content.
#----------------------------------------------------------------------------------------------------------------#
CMake Error at C:/Users/Dio/Downloads/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBLAS.cmake:699 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  C:/Users/Dio/Downloads/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindLAPACK.cmake:162 (find_package)
  CMakeLists.txt:425 (find_package)
#----------------------------------------------------------------------------------------------------------------#

so, I'm compiled LAPACK by CLAPCK.
but Where should I add it?

I'm tried add environment variables in "CMakeList.txt"
Below is the content.

#---------------------------------------------------------------------------*/
set(LAPACKE_DIR, "C:/trybuild/lapack")
set(LAPACKE_INCDIR, "C:/trybuild/lapack/include")
set(LAPACKE_LIBDIR, "C:/trybuild/lapack/lib")

#------------------------------------------------------------------------------------#
 CMake settings
#------------------------------------------------------------------------------------#
cmake_minimum_required(VERSION 2.8)

project("bitpit" CXX)

But. it would have the same error as this. How can I solve it? Thanks!

**Comment by marcocisternino** [comment]
Hi yoonil4,
Thanks for your interest in bitpit.
Looking at your error report, you are trying to build bitpit on a Windows system and it seems you don't have any BLAS library installed or cmake cannot find it.
Beware: bitpit is not tested on Windows and soon bitpit will depend on PETSc whose use  is strongly discouraged on Windows OS, https://www.mcs.anl.gov/petsc/documentation/installation.html#windows

Please, consider a Linux OS or a MacOS as OS for using bitpit, even on a virtual machine, https://www.virtualbox.org/.
However, we are working on support to Windows MinGW/CygWin and we hope it will be available as soon as possible.

Best regards,

Marco Cisternino, PhD
marco.cisternino@optimad.it
_______________________________
OPTIMAD Engineering srl
Via Giacinto Collegno 18, Torino, Italia.
+3901119719782
www.optimad.it


________________________________________
Da: yoonil4 <notifications@github.com>
Inviato: mercoledì 14 marzo 2018 02:20:55
A: optimad/bitpit
Cc: Subscribed
Oggetto: [optimad/bitpit] build error by CMake (#6)

hi, I tried to build bitpit by CMake, but I have a problem. .

Below is the content.
CMake Error at C:/Users/Dio/Downloads/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBLAS.cmake:699 (message):
A required library with BLAS API not found. Please specify library
location.
Call Stack (most recent call first):
C:/Users/Dio/Downloads/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindLAPACK.cmake:162 (find_package)
CMakeLists.txt:425 (find_package)

So, i'm compiled LAPACK by CLAPCK.
but Where should I add it?

I'm tried add environment variables in "CMakeList.txt".
Below is the content.
#---------------------------------------------------------------------------*/
set(LAPACKE_DIR, "C:/trybuild/lapack")
set(LAPACKE_INCDIR, "C:/trybuild/lapack/include")
set(LAPACKE_LIBDIR, "C:/trybuild/lapack/lib")

#------------------------------------------------------------------------------------#

CMake settings

#------------------------------------------------------------------------------------#
cmake_minimum_required(VERSION 2.8)

project("bitpit" CXX)

**Comment by yoonil4** [comment]
Thank you, I sincerely thank you for supporting and helping us.

**Comment by marcocisternino** [comment]
Hi yoonil4,
please don't take my answer as a way to abandon you. Porting bitpit to Windows is one of our task, but is not so easy for us at this moment. Your problem can be resolved setting  the cmake variable BLAS_blas_LIBRARY to the correct blas library in your system (libblas.ddl.a in MinGW). Once you did it, the same problem will stem for lapack, therefore setting LAPACK_lapack_LIBRARY to the path of liblapack.ddl.a you can solve it. Same procedure to solve the the problem arising from libxml2. You should install the dev version of this library and feed the cmake with the include dir and the library. At this point you will experience a problem with lapacke, which cannot be solved in the same way: you should comment the line in root CMakeLists.txt calling find_package(LAPACKE REQUIRED) and add and set some variables by hand. These variable are LAPACKE_DIR, LAPACKE_INCDIR, LAPACKE_LIBDIR, LAPACKE_STATIC.
Once this have been done you should be able to configure and generate.
However, some incompatibility errors will be found because of gcc MinGW compiler has not been tested yet and I'm experiencing several problems, like the definition of M_PI, the first of compiling errors.
I will look at these problems as soon as possible.
I hope this can help you a little bit.

Bests,
Marco

**Comment by marcocisternino** [comment]
yoonil4,
I have to correct my previous explanation: don't turn off the find_packge call for LAPACKE, just add and set the variables I suggested you, please. 
may I ask you what you think to do with bitpit, please?

**Comment by marcocisternino** [comment]
This issue has not seen any recent activity. I'm closing the issue, but feel free to re-open a closed issue if needed.
