### ISSUE TITLE
Set of boundary cells for coupling two meshes

### ISSUE THREAD

**Issue by asikstel** [optimad/bitpit#9]
Hi,

I've just discovered your library and find it very interesting. Actually, after a short glance at the documentation, It fits my purposes perfectly. One thing I could not see directly, however, is the following.
Suppose you want to exchange data from two solvers spatial boundaries, i.e. Solver 1 requires the data in a set of cells of Solver 2 and vice versa. Is it possible already or is it easy to implement into bitpit (probably into PABLO) in the MPI setting?

**Comment by marcocisternino** [comment]
Hi asikstel,
we are glad to know that you are trying to use bitpit.
Could you argument a little bit more, please? Do Solver 1 and solver 2 live on the same mesh but in different sub-domains of the same mesh? Do they live in different disjointed meshes and you want to couple these two meshes across their boundaries? Or do they live on different meshes (voloctrees) that cover exactly the same domain?
First case, it's easy because solvers can talk together across mesh intersections.
Second case, considering boundary domain faces (one from a mesh and the other from another mesh) that perfectly match geometrically (but with different discretizations), one could imagine to use a mapping from one surface to the other.  In order to do this, surfaces can be wrapped into a bitpit::SurfUnstructured for each one and a parallel mapping can be written from one SurfUnstructured to the other and viceversa. We are working on this mapper for another project and we can help you if you want to start developing this feature.
Third case, we have a cell mapper from one octree to another octree, covering the same domain, into the POD module of bitpit. Once you did cell mapping, you can interpolate on solver boundaries (intersections in voloctree)

**Comment by asikstel** [comment]
HI marcocisternino,
thanks a lot for your reply and good news! I mean exactly the second case and in fact on the long term I would couple multiple solvers each on a  disjoint mesh (i.e. on a network) such that also multiple solvers could be connected to one single solver at different boundaries.
Thanks also for your offer to help, this would be great! I plan to start implementing bitpit in our solver by the end of the year and would also contribute to your repo. I will let you know as soon as I finish current work and start on bitpit.

**Comment by marcocisternino** [comment]
This issue has not seen any recent activity. I'm closing the issue, but feel free to re-open a closed issue if needed.
